const BOARD_DIMENSION = 10;

const ALLOWED_SHIP_DIMENSIONS = [5, 4, 3, 3, 2];

const ALLOWED_PLAYER_TYPES = ["BOT", "HUMAN"];

export { BOARD_DIMENSION, ALLOWED_SHIP_DIMENSIONS, ALLOWED_PLAYER_TYPES };
