"use strict";

const BOARD_DIMENSION = 10;

const ALLOWED_SHIP_DIMENSIONS = [5, 4, 3, 3, 2];

const ALLOWED_PLAYER_TYPES = ["BOT", "HUMAN"];

const HORIZONTAL_ORIENTATION = "H";

const VERTICAL_ORIENTATION = "V";

const PAUSE_DURATION = 1000;

export {
  BOARD_DIMENSION,
  ALLOWED_SHIP_DIMENSIONS,
  ALLOWED_PLAYER_TYPES,
  HORIZONTAL_ORIENTATION,
  VERTICAL_ORIENTATION,
  PAUSE_DURATION
};
